name: Feature port request
description: Request a feature be ported from another codebase
title: []
labels: ["feature request"]
assignees:
  - SpypigDev
body:
  - type: textarea
    id: port-req-origin
    attributes:
      label: Name of its origin codebase or specific PR
      placeholder: "Just its name, dont link it"
    validations:
      required: true
  - type: textarea
    id: port-req-desc
    attributes:
      label: Feature port request
      placeholder: Describe which features/code/systems should be ported.
    validations:
      required: true
  - type: input
    id: port-req-prereq
    attributes:
      label: Is this a pre-req of your PR?
      placeholder: "If yes, link your PR here"
